service: prototype
provider:
  name: aws
  stage: alpha
  region: us-west-2
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  auth0:
    handler: handler.authenticate
    environment:
      A0_ALGORITHM: RS256
      A0_DOMAIN: mhp.us.auth0.com
  index:
    handler: handler.index
    events:
      - http:
          path: /
          method: get
          authorizer: auth0
          cors: true
      - http:
          path: /{proxy+}
          method: any
          authorizer: auth0
          cors: true

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
